- name: grant_icat_user_permissions_on_DB
  postgresql_privs:
    database: "{{ irods_catalog_db_name }}"
    privs: ALL
    type: table
    objs: ALL_IN_SCHEMA
    host: "{{ irods_catalogue_db_host }}"
    roles: public
  become_user: postgres

- name: deploy_irods_pam_configuration
  template:
    src: pam_irods.j2
    dest: /etc/pam.d/irods
    mode: 0644
    owner: root 
