- name: InstallSomePrerequirements
  include: prereq.yml

- name: ConfigureIrodsRepository
  include: irods-repo.yml

- name: configure_iCAT_database
  include:  irods_icat.yml
  when:  ansible_fqdn == irods.catalogue.address
  tags: 
  - irods_cat
  - role_irodsServer
  - irods

- name: install_irods_server
  include: irods_install.yml
  tags:
  - role_irodsServer
  - irods
  - install

- name: configure_irods_server
  include: irods_configure.yml
  tags:
  - role_irodsServer
  - irods
  - configure

